import Nav from '@/components/layouts/nav'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/components/layouts/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={` ${inter.className}`} >
        <div className={`flex min-h-screen items-center flex-col overflow-hidden p-10`}>
          <Nav/>
          {children}
        </div>
        <Footer/>        
      </body>
    </html>
  )
}
